#!/usr/bin/python3

import sys
import math

with open(sys.argv[1], "r") as f:
    numbers = f.readlines()

for num in numbers:
    num = int(num)
    if num % 2:
        for p in range(3, num, 2):
            if num % p == 0:
                q = num / p
                break
    else:
        q = num / 2
        p = 2
    q = int(q)
    print(f"{num}={p}*{q}")
